Add python examples to ctest

diff --git a/dawn/examples/python/python-test.sh.in b/dawn/examples/python/python-test.sh.in
--- a/dawn/examples/python/python-test.sh.in
+++ b/dawn/examples/python/python-test.sh.in
@@ -2,6 +2,8 @@
     echo 'SIR Python example @example@ did not run. TEST failed.' && exit 1
 }
 
-diff @example@.cpp @CMAKE_CURRENT_SOURCE_DIR@/data/@example@_ref.cpp || {
-    echo 'SIR Python example @example@ TEST failed.' && exit 1
-}
+if @verify@; then
+    diff @example@.cpp @CMAKE_CURRENT_SOURCE_DIR@/data/@example@_reference.cpp || {
+        echo 'SIR Python example @example@ TEST failed.' && exit 1
+    }
+fi
